### ISSUE TITLE
为什么下拉刷新哪里会留白呢？

### ISSUE THREAD

**Issue by wangdabaoqq** [Ryqsky/cnode_vue#1]

**Comment by Ryqsky** [comment]
为什么会留白？体验问题，特意加的。单单一句话，我有点难理解你想表达什么意思。

具体原因你可以直接看源码。

![default](https://user-images.githubusercontent.com/8382136/27024457-332a3f42-4f89-11e7-8dc4-a322ae655f17.png)

如果再深一层，你可以选择看vux源码 https://github.com/airyland/vux

**Comment by wangdabaoqq** [comment]
特意加的？那我明白了。
